[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "mpcq/version.py"
write_to_template = "__version__ = '{version}'"

[tool.isort]
profile = "black"
