name: Publish package

on:
  push:
    branches:
      - main
      - prerelease*
      - "*"
    tags:
      - "*"

jobs:
  # Publish a package to private PyPI
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Authenticate to gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify gcloud credentials
        run: gcloud auth list

      - name: Install auth dependencies for using Google Artifact Registry
        run: |
          python -m pip install --upgrade pip
          pip install keyring keyrings.google-artifactregistry-auth

      - name: Configure pip to use Google Artifact Registry
        run: |
          cat << EOF > ~/.config/pip/pip.conf
          [global]
          index-url = https://us-west1-python.pkg.dev/moeyens-thor-dev/ai-pypi/
          EOF

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build and publish package
        run: |
          python setup.py sdist bdist_wheel
          python -m twine upload --repository-url https://us-west1-python.pkg.dev/moeyens-thor-dev/ai-pypi/ dist/*
